name: Go CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test (Go 1.25.2)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.2"
          check-latest: true
          cache: true

      - name: Clear GOCOVERDIR if set
        run: unset GOCOVERDIR

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests with coverage
        run: |
          mkdir -p ./.coverage
          go test ./... -race -covermode=atomic -coverprofile=.coverage/coverage.out

      - name: Show total coverage and write summary
        id: cover
        run: |
          total=$(go tool cover -func=.coverage/coverage.out | awk '/total:/ {print $3}')
          echo "total_coverage=$total" >> $GITHUB_OUTPUT
          {
            echo "### Coverage Summary"
            echo ""
            echo "- Total: **$total**"
            echo ""
            echo "\`\`\`"
            go tool cover -func=.coverage/coverage.out
            echo "\`\`\`"
          } >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-go1.25.2
          path: .coverage/coverage.out
          if-no-files-found: error

      - name: Upload to Codecov (public repos work tokenless)
        uses: codecov/codecov-action@v4
        with:
          files: .coverage/coverage.out
          flags: go1.25.2
          fail_ci_if_error: true
